// <auto-generated />
using EMarketWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMarketWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240220013551_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMarketWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Clothing & Apparel"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Books & Media"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Jewelry & Accessories"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
